/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts */
/***********************************************/

export default {
  API_URL: 'https://api.cardvest.ng/api/v2',
  ENV: 'staging',
  MXP_PRO_TOKS: '406f69b81f42a113baade56967f62ec1',
  ADJ_TOKEN: 'vg0lx4h6nkzk',
  ACC_CRT: '1l8oak',
  ACC_GC_SL: 'h70z24',
  ACC_GC_BY: 'ee459k',
  ACC_FN_WI: 'eeqj5x',
};
