/* eslint-disable */
/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts */
/***********************************************/

export default {
  API_URL: 'https://app.cardvest.ng/api/v1',
  ENV: 'development',
};
