/* eslint-disable */
/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts */
/***********************************************/

export default {
  API_URL: 'https://reqres.in/api',
  ENV: 'development',
};
